sonar.projectKey=PetMatch
sonar.projectName=PetMatch
sonar.projectVersion=1.0

# Onde estão os códigos-fonte (ignorar testes aqui)
sonar.sources=src
sonar.exclusions=src/__tests__/**,src/**/*.test.ts,src/**/*.spec.ts

# Onde estão os testes
sonar.tests=src
sonar.test.inclusions=src/__tests__/**,src/**/*.test.ts,src/**/*.spec.ts

# Caminho para o relatório de cobertura de testes gerado pelo Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
